services:
  db:
    image: postgres:latest
    container_name: conduit_db
    ports:
      - "5432:5432"
    volumes:
      - conduit_db_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: conduit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  conduit_db_data:
